# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-06 10:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('signature_provided_org', models.IntegerField(default=0)),
                ('signature_left_org', models.IntegerField(default=0)),
                ('signature_provided_per', models.IntegerField(default=0)),
                ('signature_left_per', models.IntegerField(default=0)),
                ('pan', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('is_staff', models.BooleanField(default=True)),
                ('has_org', models.BooleanField(default=False)),
                ('address', models.TextField(default='NULL')),
                ('gender', models.CharField(default='NULL', max_length=1)),
                ('dob', models.DateField(default='2015-01-01')),
                ('date_org_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('website', models.CharField(default='NULL', max_length=50)),
                ('contact_mail', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default='2015-01-01 12:00:00.0000')),
                ('pan', models.CharField(max_length=15)),
                ('admin', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=100)),
                ('latest_signature_purchase', models.IntegerField(default=0)),
                ('total_signature_purchased', models.IntegerField(default=0)),
                ('signatures_left', models.IntegerField(default=0)),
                ('signatures_used', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_result_phone_number', models.BooleanField(default=True)),
                ('professional_result_phone_number', models.BooleanField(default=True)),
                ('profile_view_phone_number', models.BooleanField(default=True)),
                ('personal_result_email', models.BooleanField(default=True)),
                ('professional_result_email', models.BooleanField(default=True)),
                ('profile_view_email', models.BooleanField(default=True)),
                ('personal_result_address', models.BooleanField(default=True)),
                ('professional_result_address', models.BooleanField(default=True)),
                ('profile_view_address', models.BooleanField(default=True)),
                ('personal_result_gender', models.BooleanField(default=False)),
                ('profile_view_gender', models.BooleanField(default=True)),
                ('show_dob', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=100)),
                ('addressed_to', models.CharField(max_length=100)),
                ('created', models.CharField(default='NULL', max_length=100)),
                ('subject', models.TextField(blank=True, default='NULL')),
                ('signatory', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('flag_reason', models.TextField(default='NULL')),
                ('flagged_by', models.TextField(default='NULL')),
                ('comments', models.TextField(blank=True, default='NULL')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=True)),
                ('invalidated_by', models.CharField(blank=True, default='NULL', max_length=200)),
                ('invalidated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('invalidated_reason', models.TextField(blank=True, default='NULL')),
                ('org', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='winker.Org')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='winker.Org'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
