# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 09:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('winker', '0005_auto_20160807_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_org_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 7, 9, 46, 31, 899562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, default='NULL', max_length=10),
        ),
    ]
