# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winker', '0006_auto_20160807_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_org_created',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
