# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winker', '0008_user_org_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatures',
            name='is_haulted',
            field=models.BooleanField(default=False),
        ),
    ]
