# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winker', '0009_signatures_is_haulted'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='show_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='org',
            name='show_eco_savings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='org',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='org',
            name='show_website',
            field=models.BooleanField(default=True),
        ),
    ]
