# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winker', '0010_auto_20160812_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='show_staff_mail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='org',
            name='show_staff_phone',
            field=models.BooleanField(default=False),
        ),
    ]
