# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winker', '0011_auto_20160812_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatures',
            name='hault_user_permission',
            field=models.BooleanField(default=False),
        ),
    ]
