# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('winker', '0012_signatures_hault_user_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='NULL', max_length=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.TextField(default='NULL')),
                ('targeted_audience', models.TextField(default='NULL')),
                ('seen', models.BooleanField(default=False)),
                ('seen_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_user', models.TextField(default='NULL')),
                ('request_signature', models.TextField(default='NULL')),
                ('request_operation', models.TextField(default='NULL')),
                ('code', models.TextField(default='NULL')),
                ('request_denied', models.BooleanField(default=False)),
                ('org_related', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='winker.Org')),
            ],
        ),
    ]
