# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winker', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.TextField(default='NULL'),
        ),
    ]
