# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-14 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winker', '0016_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_payment',
            field=models.IntegerField(default=0),
        ),
    ]
